/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsImportIdRouteImport } from './routes/reports.$importId'
import { Route as ImportsNewRouteImport } from './routes/imports.new'
import { Route as ImportsImportIdRouteImport } from './routes/imports.$importId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsImportIdRoute = ReportsImportIdRouteImport.update({
  id: '/reports/$importId',
  path: '/reports/$importId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsNewRoute = ImportsNewRouteImport.update({
  id: '/imports/new',
  path: '/imports/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsImportIdRoute = ImportsImportIdRouteImport.update({
  id: '/imports/$importId',
  path: '/imports/$importId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/imports/$importId': typeof ImportsImportIdRoute
  '/imports/new': typeof ImportsNewRoute
  '/reports/$importId': typeof ReportsImportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/imports/$importId': typeof ImportsImportIdRoute
  '/imports/new': typeof ImportsNewRoute
  '/reports/$importId': typeof ReportsImportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/imports/$importId': typeof ImportsImportIdRoute
  '/imports/new': typeof ImportsNewRoute
  '/reports/$importId': typeof ReportsImportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/imports/$importId'
    | '/imports/new'
    | '/reports/$importId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/imports/$importId'
    | '/imports/new'
    | '/reports/$importId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/imports/$importId'
    | '/imports/new'
    | '/reports/$importId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ImportsImportIdRoute: typeof ImportsImportIdRoute
  ImportsNewRoute: typeof ImportsNewRoute
  ReportsImportIdRoute: typeof ReportsImportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$importId': {
      id: '/reports/$importId'
      path: '/reports/$importId'
      fullPath: '/reports/$importId'
      preLoaderRoute: typeof ReportsImportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/new': {
      id: '/imports/new'
      path: '/imports/new'
      fullPath: '/imports/new'
      preLoaderRoute: typeof ImportsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/$importId': {
      id: '/imports/$importId'
      path: '/imports/$importId'
      fullPath: '/imports/$importId'
      preLoaderRoute: typeof ImportsImportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ImportsImportIdRoute: ImportsImportIdRoute,
  ImportsNewRoute: ImportsNewRoute,
  ReportsImportIdRoute: ReportsImportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
